football/football/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('teams.urls', namespace='teams')),
    path('match/', include('games.urls', namespace='games')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    # path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

football/games/urls.py
from django.urls import path

from . import views

app_name = 'games'

urlpatterns = [
    path('', views.match, name='match_list'),
    path('<int:match_id>/', views.match_detail, name='match_detail'),
]

football/teams/urls.py
from django.urls import path

from . import views

app_name = 'teams'

urlpatterns = [
    path('', views.index, name='index'),
    path('teams/', views.teams, name='teams_list'),
    path('teams/<int:team_id>/', views.team_detail, name='team_detail'),
    path('my_team/', views.my_team, name='my_team'),
    path('players/', views.players, name='players_list'),
    path('players/<int:player_id>/', views.player_detail, name='player_detail'),
    path('profile/<str:username>/', views.profile, name='profile'),
]

football/teams/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth import get_user_model

User = get_user_model()


class Team(models.Model):
    '''Команда.'''
    name = models.CharField(
        verbose_name='Название команды',
        max_length=255,
    )
    city = models.CharField(
        verbose_name='Команда из города',
        max_length=255,
    )
    coach = models.OneToOneField(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='team',
    )
    emblem = models.ImageField(
        verbose_name='Эмблема клуба',
        upload_to='teams/',
        blank=True,
        null=True,
    )
    stadium = models.CharField(
        verbose_name='Название стадиона команды',
        max_length=255,
    )
    capacity = models.PositiveIntegerField(
        verbose_name='Вместимость стадиона',
        default=5000,
    )
    money = models.PositiveIntegerField(
        verbose_name='Деньги на счету команды',
        default=25000000,
    )

    def __str__(self) -> str:
        return self.name


class Player(models.Model):
    '''Футболист, футбольный игрок, персонаж.'''
    POSITION_CHOICES = (
        ('ВР', 'Вратарь'),
        ('ЗЩ', 'Защитник'),
        ('ПЗ', 'Полузащитник'),
        ('НП', 'Нападающий'),
    )
    COUNTRY_CHOICES = (
        ('RU', 'Россия'),
        ('EN', 'Англия'),
    )
    name = models.CharField(
        verbose_name='Футболист',
        max_length=255,
    )
    age = models.PositiveSmallIntegerField(
        verbose_name='Возраст футболиста',
        validators=(
            MaxValueValidator(settings.MAX_AGE_PLAYER, 'Сделай помоложе'),
            MinValueValidator(settings.MIN_AGE_PLAYER, 'Сделай постарше'),
        )
    )
    power = models.PositiveSmallIntegerField(
        verbose_name='Сила футболиста',
        validators=(
            MaxValueValidator(settings.MAX_POWER_PLAYER, 'Слишком сильный'),
            MinValueValidator(settings.MIN_POWER_PLAYER, 'Слишком слабый'),
        )
    )
    position = models.CharField(
        max_length=2,
        choices=POSITION_CHOICES,
    )
    country = models.CharField(
        max_length=2,
        choices=COUNTRY_CHOICES,
    )
    fatigue = models.PositiveSmallIntegerField(
        verbose_name='Усталость футболиста',
        default=0,
        editable=False,
    )
    team = models.ForeignKey(
        Team,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='players',
    )

    def calculate_cost(self):
        """Считает цену игрока."""
        return (40 - self.age) * self.power * 1000

football/teams/forms.py
from django import forms


class TakeControlForm(forms.Form):
    team_id = forms.IntegerField(widget=forms.HiddenInput())

football/teams/views.py
from django.shortcuts import get_object_or_404, redirect, render

from .models import Player, Team
from .forms import TakeControlForm


def index(request):
    """Главная страница."""
    return render(request, 'teams/index.html')


def teams(request):
    """Выводит список всех команд."""
    teams = Team.objects.all()
    context = {
        'teams': teams,
    }
    return render(request, 'teams/teams_list.html', context)


def team_detail(request, team_id):
    """Выводит информацию о выбранной команде."""
    team = get_object_or_404(Team, id=team_id)
    if request.method == 'POST':
        form = TakeControlForm(request.POST)
        if form.is_valid():
            team.coach = request.user
            team.save()
            return redirect('teams:players_list')
    else:
        form = TakeControlForm(initial={'team_id': team_id})
    context = {
        'team': team,
        'form': form,
    }
    return render(request, 'teams/team_detail.html', context)


def my_team(request):
    """Выводит информацию о команде текущего пользователя."""
    team = request.user.team
    context = {
        'team': team,
    }
    return render(request, 'teams/my_team.html', context)


def players(request):
    """Выводит список всех игроков.
    Можно передавать доп параметр sort_param
    для сортировки игроков.
    """
    sort_param = request.GET.get('sort')
    if sort_param and sort_param in ['calculate_cost', '-calculate_cost']:
        players = Player.objects.all()
        if sort_param[0] != '-':
            players = sorted(players, key=lambda x: x.calculate_cost(), reverse=True)
            flag = True
        else:
            players = sorted(players, key=lambda x: x.calculate_cost())
            flag = False
    elif sort_param:
        players = Player.objects.order_by(sort_param)
        if sort_param[0] != '-':
            flag = True
        else:
            flag = False
    else:
        players = Player.objects.all()
        flag = False
    context = {
        'players': players,
        'flag': flag,
    }
    return render(request, 'teams/players_list.html', context)


def player_detail(request):
    """Выводит информацию о выбранном игроке."""
    pass


def profile(request):
    """Профиль выбранного пользователя."""
    pass

football/templates/teams/index.html
{% extends 'base.html' %}

{% block title %}
  Главная страница
{% endblock %}

{% block content %}
  <div class="container py-5">
    Див
  </div>
{% endblock %}

football/templates/teams/my_team.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  {{ team }}
{% endblock %}

{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Название ФК: {{ team.name }}
        </li>
        <li class="list-group-item">
          Город: {{ team.city }}
        </li>
        <li class="list-group-item">
          Тренер: {{ team.coach }}
        </li>
        <li class="list-group-item">
          Стадион: {{ team.stadium }}
        </li>
        <li class="list-group-item">
          Вместимость: {{ team.capacity }}
        </li>
        <li class="list-group-item">
          Деньги: {{ team.money }}
        </li>
        <!-- если у поста есть группа -->
        {% comment %} {% if post.group %}
        <li class="list-group-item">
          {{ post.group }}<!-- Название группы -->
          <a href="{% url 'posts:group_list' post.group.slug %}">
            все записи группы
          </a>
          {% endif %}
        </li>
        <li class="list-group-item">Автор: {{ post.author.get_full_name }}</li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span>{{ post.author.posts_author.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li> {% endcomment %}
      </ul>
    </aside>
    <article class="col-12 col-md-3">
      {% thumbnail team.emblem "300x300" crop="center" quality=100 upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      {% comment %} <p>
        {{ post.text }}
      </p>
      {% if request.user == post.author %}
      <form method="get" action="{% url 'posts:post_edit' post.id %}">
        <button type="submit" class="btn btn-primary">
          Редактировать пост
        </button>
      </form>
      {% endif %} {% endcomment %}
    </article>
  </div>

<!-- Форма добавления комментария -->
{% comment %} {% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %} {% endcomment %}
{% endblock content %}

football/templates/teams/players_list.html
<style>
  table {
    width: 100%;
    border-collapse: collapse;
  }
  th, td {
    padding: 8px;
    border: 1px solid black;
  }
  tr:nth-child(even) {
    background-color: #f2f2f2;
  }
  a {
    text-decoration: none !important;
  }
</style>
  
{% extends 'base.html' %}

{% block title %}
  Игроки
{% endblock %}

{% block content %}
  <div class="container py-5">
    <table>
      <tr>
        {% if flag == False %}
          <th><a href="{% url 'teams:players_list' %}?sort=name">Имя</a></th>          
          <th><a href="{% url 'teams:players_list' %}?sort=age">Возраст</a></th>
          <th><a href="{% url 'teams:players_list' %}?sort=power">Сила</a></th>
          <th><a href="{% url 'teams:players_list' %}?sort=calculate_cost">Цена</a></th>
          <th><a href="{% url 'teams:players_list' %}?sort=position">Позиция</a></th>
          <th><a href="{% url 'teams:players_list' %}?sort=country">Страна</a></th>
          <th><a href="{% url 'teams:players_list' %}?sort=fatigue">Усталость</a></th>
          <th><a href="{% url 'teams:players_list' %}?sort=team">Команда</a></th>
        {% else %}
          <th><a href="{% url 'teams:players_list' %}?sort=-name">Имя</a></th>          
          <th><a href="{% url 'teams:players_list' %}?sort=-age">Возраст</a></th>
          <th><a href="{% url 'teams:players_list' %}?sort=-power">Сила</a></th>
          <th><a href="{% url 'teams:players_list' %}?sort=-calculate_cost">Цена</a></th>
          <th><a href="{% url 'teams:players_list' %}?sort=-position">Позиция</a></th>
          <th><a href="{% url 'teams:players_list' %}?sort=-country">Страна</a></th>
          <th><a href="{% url 'teams:players_list' %}?sort=-fatigue">Усталость</a></th>
          <th><a href="{% url 'teams:players_list' %}?sort=-team">Команда</a></th>
        {% endif %}
      </tr>
      {% for player in players %}
        <tr>
          <td>{{ player.name }}</td>
          <td>{{ player.age }}</td>
          <td>{{ player.power }}</td>
          <td>{{ player.calculate_cost }}</td>
          <td>{{ player.position }}</td>
          <td>{{ player.country }}</td>
          <td>{{ player.fatigue }}</td>
          {% if not player.team %}
            <form method="post">
            {% csrf_token %}
              <td>
                <input type="hidden" name="team_id" value="{{ form.team_id.value }}">
                <button type="submit" class="btn btn-primary">
                  Купить игрока
                </button>
              </td>
            </form>
          {% else %}
            <td>{{ player.team }}</td>
          {% endif %}
        </tr>
      {% endfor %}
    </table>
  </div>

  {% comment %} <button id="sortButton" class="btn btn-primary">Сортировать по возрасту</button>

  <script>
    document.getElementById('sortButton').addEventListener('click', function() {
      var table, rows, switching, i, x, y, shouldSwitch;
      table = document.querySelector('table');
      switching = true;
      while (switching) {
        switching = false;
        rows = table.rows;
        for (i = 1; i < (rows.length - 1); i++) {
          shouldSwitch = false;
          x = rows[i].querySelectorAll('td')[1]; // Возраст игрока
          y = rows[i + 1].querySelectorAll('td')[1]; // Возраст следующего игрока
          if (Number(x.innerHTML) > Number(y.innerHTML)) {
            shouldSwitch= true;
            break;
          }
        }
        if (shouldSwitch) {
          rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
          switching = true;
        }
      }
    });
  </script> {% endcomment %}

{% endblock content %}

football/templates/teams/team_detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  {{ team }}
{% endblock %}

{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Название ФК: {{ team.name }}
        </li>
        <li class="list-group-item">
          Город: {{ team.city }}
        </li>
        <li class="list-group-item">
          Тренер: {{ team.coach }}
        </li>
        <li class="list-group-item">
          Стадион: {{ team.stadium }}
        </li>
        <li class="list-group-item">
          Вместимость: {{ team.capacity }}
        </li>
        {% if not team.coach and not request.user.team %}
        <form method="post">
          {% csrf_token %}
          <input type="hidden" name="team_id" value="{{ form.team_id.value }}">
          <button type="submit" class="btn btn-primary">
            Взять на управление эту команду
          </button>
        </form>
        {% endif %}
        <!-- если у поста есть группа -->
        {% comment %} {% if post.group %}
        <li class="list-group-item">
          {{ post.group }}<!-- Название группы -->
          <a href="{% url 'posts:group_list' post.group.slug %}">
            все записи группы
          </a>
          {% endif %}
        </li>
        <li class="list-group-item">Автор: {{ post.author.get_full_name }}</li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span>{{ post.author.posts_author.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li> {% endcomment %}
      </ul>
    </aside>
    <article class="col-12 col-md-3">
      {% thumbnail team.emblem "300x300" crop="center" quality=100 upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      {% comment %} <p>
        {{ post.text }}
      </p>
      {% if request.user == post.author %}
      <form method="get" action="{% url 'posts:post_edit' post.id %}">
        <button type="submit" class="btn btn-primary">
          Редактировать пост
        </button>
      </form>
      {% endif %} {% endcomment %}
    </article>
  </div>

<!-- Форма добавления комментария -->
{% comment %} {% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %} {% endcomment %}
{% endblock content %}

football/templates/teams/teams_list.html
<style>
  table {
    width: 100%;
    border-collapse: collapse;
  }
  th, td {
    padding: 8px;
    border: 1px solid black;
  }
  tr:nth-child(even) {
    background-color: #f2f2f2;
  }
  a {
    text-decoration: none !important;
  }
</style>

{% extends 'base.html' %}
{% load thumbnail %}
  
{% block title %}
  Команды
{% endblock %}

{% block content %}
  <div class="container py-5">
    <table>
      <tr>
        <th>Эмблема</th>
        <th>Название</th>
        <th>Город</th>
        <th>Тренер</th>
        <th>Стадион</th>
        <th>Вместимость</th>
      </tr>
      {% for team in teams %}
      <tr>
        <td>
          {% thumbnail team.emblem "30x30" crop="center" quality=100 upscale=True as im %}
            <img src="{{ im.url }}">
          {% endthumbnail %}
        </td>
        <td><a href="{% url 'teams:team_detail' team.id %}">{{ team.name }}</a></td>
        <td>{{ team.city }}</td>
        <td>{{ team.coach }}</td>
        <td>{{ team.stadium }}</td>
        <td>{{ team.capacity }}</td>
      </tr>
      {% endfor %}
    </table>
  </div>
{% endblock content %}
  