football/football/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('teams.urls', namespace='teams')),
    path('match/', include('games.urls', namespace='games')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    # path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

football/games/urls.py
from django.urls import path

from . import views

app_name = 'games'

urlpatterns = [
    path('', views.match, name='match_list'),
    path('<int:match_id>/', views.match_detail, name='match_detail'),
]

football/teams/urls.py
from django.urls import path

from . import views

app_name = 'teams'

urlpatterns = [
    path('', views.index, name='index'),
    path('teams/', views.teams, name='teams_list'),
    path('teams/<int:team_id>/', views.team_detail, name='team_detail'),
    path('my_team/', views.my_team, name='my_team'),
    path('players/', views.players, name='players_list'),
    path('players/<int:player_id>/', views.player_detail, name='player_detail'),
    path('profile/<str:username>/', views.profile, name='profile'),
]

football/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

football/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>
    © {{ year }} Copyright <span style="color:red">Footbal</span>Coach
  </p>
</footer>

football/templates/includes/form_errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">{{ error|escape }}</div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">{{ error|escape }}</div>
  {% endfor %}
{% endif %}

football/templates/includes/header.html
{% load static %} 
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'teams:index' %}">
    <img src="{% static 'img/logo.png' %}" width="30" height="30"
    class="d-inline-block align-top" alt="">
    <span style="color:red">Football</span>Coach
    </a>
      <ul class="nav nav-pills">
        {% with request.resolver_match.view_name as view_name %}
        {% comment %} <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'about:author' %}
          active{% endif %}" href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}
          active{% endif %}" href="{% url 'about:tech' %}">Технологии
          </a>
        </li> {% endcomment %}
        {% if request.user.is_authenticated %}
        {% if request.user.team %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'teams:my_team' %}
          active{% endif %}" href="{% url 'teams:my_team' %}">
            Моя команда
          </a>
        </li>
        {% endif %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'teams:teams_list' %}
          active{% endif %}" href="{% url 'teams:teams_list' %}">
            Команды
          </a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'teams:players_list' %}
          active{% endif %}" href="{% url 'teams:players_list' %}">
            Игроки
          </a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'games:match_list' %}
          active{% endif %}" href="{% url 'games:match_list' %}">
            Игры
          </a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light
            {% if view_name  == 'users:password_change_form' %}
            active{% endif %}" href="{% url 'users:password_change_form' %}">
            Изменить пароль
          </a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:logout' %}">
            Выйти
          </a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:login' %}
            active{% endif %}" href="{% url 'users:login' %}">Войти
          </a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:signup' %}
          active{% endif %}" href="{% url 'users:signup' %}">Регистрация
          </a>
        </li>
        {% endif %}
        {% endwith %}
      </ul>
  </div>
</nav>

football/templates/includes/label.html
{% load user_filters %}
<div class="form-group row my-3"
  {% if field.field.required %} 
    aria-required="true"
  {% else %}
    aria-required="false"
  {% endif %}
>
  <label for="{{ field.id_for_label }}">
    {{ field.label }}
      {% if field.field.required %}
        <span class="required text-danger">*</span>
      {% endif %}
  </label>
  <div>
  {{ field|addclass:'form-control' }}
    {% if field.help_text %}
      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
    {% endif %}
  </div>
</div>